version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: monday
      time: '00:00'
    directory: /
    allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: 'chore'
    labels:
      - Dependencies
  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: monday
      time: '00:00'
    directory: /
    allow:
      - dependency-type: direct
    versioning-strategy: increase
    commit-message:
      include: scope
      prefix: 'chore'
    labels:
      - Dependencies
