/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "identityD1": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "passportKV": {
      "type": "sst.cloudflare.Kv"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}